import React, { useEffect } from "react"
import { useForm } from 'react-hook-form'

//next
import Head from "next/head"
import Image from "next/image"

import { useRouter } from "next/router"



export default function Sair() {

    const router = useRouter()

    const labelForm = () => {
        document.querySelector('.form-group label').classList.add('label-form')
    }

    const { register, handleSubmit, watch, formState: {errors} } = useForm()

    const onSubmit = (data) => {
        console.log(data.cnpj)

        if(!data.cnpj || typeof data.cnpj == undefined || data.cnpj == null || data.cnpj == '') {
            
        }
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="viewport" content="width=device-width, initial-scale=1" />

                <meta name="description" content="Generated by create next app" />                
                <link rel="icon" href="/vtal-icon.png" />
            </Head>

            <section className="">
                <section className="container d-flex justify-content-center align-items-center" style={{height: '100vh'}}>
                    <form onSubmit={handleSubmit(onSubmit)} className="border rounded-2 p-4" style={{maxWidth: '320px'}}>
                        <div className="text-center pt-3">
                            <Image src='/vtal-icon.png' width={25} height={25}></Image>
                        </div>
                        <div className="text-center py-3 ">
                            <p>Olá, seja bem-vindo!</p>
                            <small style={{fontSize: '11.5px', lineHeight: '11.5px'}}>No Portal Cliente V.tal, você garante agilidade, rapidez e eficiência para gerenciar seus serviços.</small>
                        </div>
                        <div className="form-group">
                            <label className="" htmlFor="cnpj">CNPJ</label>
                            <input {...register("cnpj")} onClick={labelForm} className="form-control" type="tel" name="cnpj" id="cnpj" />
                        </div>
                        <small style={{color: 'red', display: 'block', padding: '5px 0 0 5px', fontSize: '10px'}}>O campo CNPJ é obrigatório</small>
                        <button type="submit" className="btn w-100 my-3" style={{backgroundColor: '#454543', color: '#ffffff'}}>Acessar</button>
                    </form>
                </section>
            </section>
        </>
    )
}